#!/usr/bin/env bash
# Stop Hook — retitle the auto-created resume shortcut and write the summary.
#
# on-session-start-shortcut.sh guarantees a shortcut exists, but names it
# "Untitled session" because at SessionStart there is no topic yet. This hook
# runs when the turn ends, derives a real title from the transcript, renames the
# .command, and writes the Readable/*.md summary required by SOP step 6.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "$SCRIPT_DIR/lib/sibyl-hook-utils.sh"

INPUT=$(sibyl_read_hook_input)
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // ""' 2>/dev/null)
TRANSCRIPT=$(echo "$INPUT" | jq -r '.transcript_path // ""' 2>/dev/null)
[ -n "$SESSION_ID" ] || exit 0

CONV_DIR="$HOME/Desktop/Sibyl Projects/Conversations"
[ -d "$CONV_DIR" ] || exit 0

# Locate this session's shortcut.
SC=$(grep -rl "$SESSION_ID" "$CONV_DIR"/*.command 2>/dev/null | head -1)
[ -n "$SC" ] || exit 0

# Only retitle placeholders — never rename a shortcut already given a real name.
case "$(basename "$SC")" in
    *"Untitled session"*) ;;
    *) exit 0 ;;
esac

[ -n "$TRANSCRIPT" ] && [ -f "$TRANSCRIPT" ] || \
    TRANSCRIPT="$HOME/.claude/projects/-Users-mackenzieboi-sibyl-research-system/$SESSION_ID.jsonl"
[ -f "$TRANSCRIPT" ] || exit 0

# Derive a title from the first substantive user message.
TITLE=$("$SIBYL_PYTHON" - "$TRANSCRIPT" <<'PY' 2>/dev/null
import json, re, sys
def clean(s):
    s = re.sub(r"<[^>]+>", " ", s)                 # command-caveat / xml wrappers
    s = re.sub(r"[/\\:*?\"<>|]", " ", s)           # filename-hostile chars
    s = re.sub(r"\s+", " ", s).strip()
    return s
for line in open(sys.argv[1], errors="ignore"):
    try: d = json.loads(line)
    except Exception: continue
    if d.get("type") != "user" or d.get("isSidechain"): continue
    c = (d.get("message") or {}).get("content")
    txt = ""
    if isinstance(c, str): txt = c
    elif isinstance(c, list):
        for b in c:
            if isinstance(b, dict) and b.get("type") == "text":
                txt = b.get("text", ""); break
    txt = clean(txt)
    # Skip tool-result noise, slash commands and local-command wrappers.
    if len(txt) < 12 or txt.startswith(("/", "Caveat", "[Request interrupted")): continue
    print(txt[:60].strip())
    break
PY
)
[ -n "$TITLE" ] || exit 0

DATE=$(basename "$SC" | sed -n 's/^▶️ \([0-9-]\{10\}\).*/\1/p')
[ -n "$DATE" ] || DATE=$(date +%Y-%m-%d)

NEW="$CONV_DIR/▶️ $DATE - $TITLE.command"
[ -e "$NEW" ] && exit 0

mv "$SC" "$NEW" 2>/dev/null || exit 0
# Keep the header comment consistent with the new filename.
sed -i '' "2s|.*|# ▶️ $DATE - $TITLE|" "$NEW" 2>/dev/null
chmod +x "$NEW" 2>/dev/null
bash -n "$NEW" 2>/dev/null || exit 0

# SOP step 6: readable summary alongside the shortcut.
SUM="$CONV_DIR/Readable/$DATE - $TITLE.md"
if [ ! -f "$SUM" ]; then
    {
        echo "# $TITLE"
        echo
        echo "- **Date:** $DATE"
        echo "- **Session:** \`$SESSION_ID\`"
        echo "- **Resume:** \`▶️ $DATE - $TITLE.command\`"
        echo "- **Transcript:** \`$TRANSCRIPT\`"
        echo
        echo "_Auto-generated by on-stop-shortcut.sh. Ask Javis to expand this into a"
        echo "full summary if this conversation is worth writing up._"
    } > "$SUM" 2>/dev/null
fi
exit 0
